### ISSUE TITLE
No longer connecting to database

### ISSUE THREAD

**Issue by TheGamersBrew** [GuusLieben/Heads-Evolved#1]
When trying to find new heads now just shows as still obtaining heads from database. please wait... I'm guessing this is cause plug in no longer connects to the database. 
![image](https://user-images.githubusercontent.com/77638191/168384218-2d5610e6-8473-4245-a0cc-7b4413ebae6e.png)

**Comment by poqdavid** [comment]
@TheGamersBrew This https://github.com/GuusLieben/Heads-Evolved/pull/2 should fix the problem I tested and it works
